---
- name: Install k3s binary
  become: true
  copy:
    src: "{{ playbook_dir }}/../files/k3s"
    dest: /usr/local/bin/k3s
    mode: "0755"
    owner: root
    group: root

- name: Install k3s setup script
  become: true
  copy:
    src: "{{ playbook_dir }}/../files/install-k3s.sh"
    dest: /usr/local/bin/install-k3s.sh
    mode: "0755"
    owner: root
    group: root

- name: Create k3s images directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /var/lib/rancher/k3s/agent/images/

- name: Copy the k3s images into place
  become: true
  copy:
    src: "{{ playbook_dir }}/../files/k3s-airgap-images-amd64.tar"
    dest: "/var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar"
    owner: root
    group: root

- name: Copy default container images into place
  become: true
  copy:
    src: "{{ playbook_dir }}/../files/containers/"
    dest: /var/lib/rancher/k3s/agent/images/
    owner: root
    group: root

- name: Copy RPMs
  copy:
    src: "{{ playbook_dir }}/../files/rpms"
    dest: /tmp

- name: Find all rpm files in /tmp folder
  find:
    paths: "/tmp/rpms"
    patterns: "*.rpm"
  register: rpm_files

- name: Install RPMs
  become: true
  yum:
    name: "{{ rpm_files.files | map(attribute='path') | list}}"
    state: installed
    disable_gpg_check: yes
    disablerepo: "*"
